### ISSUE TITLE
How to calibrate the camera?

### ISSUE THREAD

**Issue by saikatbsk** [carlo-/aruco-ios-demo#1]
I have successfully built this application on my iPad running iOS 10.3.3. Once the UI is open and I tap the Start button to calibrate nothing happens. I can see a message in Xcode saying calibration is starting but what to do next?

**Comment by carlo-** [comment]
Hi! You need to print a chessboard pattern like [this one](https://docs.opencv.org/2.4/_downloads/pattern.png) and move it in front of the camera during the calibration step. You may find [this video](https://youtu.be/ViPN810E0SU?t=45s) useful. Let me know if that helped!

**Comment by saikatbsk** [comment]
Thanks for the reply. I tried with the checkerboard with AR markers inside it. Will let you know after I try with the checkerboard.
