### ISSUE TITLE
How to render an image instead of the line and reactangle?

### ISSUE THREAD

**Issue by tshradheya** [carlo-/aruco-ios-demo#3]
I want to show an image based on marker id instead of the `cv::line()` and `cv::rectangle()`

Do you know how I can do it? Thanks

**Comment by carlo-** [comment]
I would look at how the function `CvDrawingUtils::draw3dCube` works (part of the Aruco source; see [here](http://docs.ros.org/electric/api/aruco_pose/html/cvdrawingutils_8cpp_source.html#l00118)). You would have to project the points of your image and draw them into the output image matrix.
