### ISSUE TITLE
cv namespace issues in MarkerDetector

### ISSUE THREAD

**Issue by backnotprop** [carlo-/aruco-ios-demo#4]
<img width="768" alt="screen shot 2019-02-13 at 8 00 32 pm" src="https://user-images.githubusercontent.com/7244317/52754950-417b2700-2fca-11e9-9229-65bc9f65d4c7.png">

About 12 errors occur all the same. Ive done the setup multiple times now.

**Comment by backnotprop** [comment]
issue is here:
```
#ifdef _DEBUG
#include <opencv2/highgui/highgui.hpp>
#endif
```

**Comment by carlo-** [comment]
The issue is that OpenCV for iOS doesn't have functions that involve windows (such as those in your screenshot). You can safely comment those out, as they are not needed for the app; I should have clarified this in the README. Let me know if that fixes the issue.

**Comment by backnotprop** [comment]
Yea this isnt really a problem, just a heads up in readme would be good for others

**Comment by lilieming** [comment]
where is the cameram_parameters.yml file?
